#server:
#  port: 8080
#
#spring:
#  application:
#    name: backend-service
#  profiles:
#    active: @spring.profiles.active@
#  datasource:
#    url: jdbc:postgresql://localhost:5432/Khach_San_Test
#    username: postgres
#    password: 1
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update # Use 'validate' or 'none' in production
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
server:
  port: 8080

spring:
  application:
    name: backend-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

#springdoc:
#  api-docs:
#    enabled: true # Bật API docs
#  swagger-ui:
#    enabled: true # Bật Swagger UI
#    path: /swagger-ui.html # Đường dẫn để truy cập Swagger UI